INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Dhabba Style Chicken Curry', NULL, 'Indian', 5, 'https://www.youtube.com/watch?v=m-CRY9fHn7o', NULL, NULL, 1, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Dhabba Style Chicken Curry' AND youtube_url = 'https://www.youtube.com/watch?v=m-CRY9fHn7o'), 'tried');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Dhabba Style Chicken Curry' AND youtube_url = 'https://www.youtube.com/watch?v=m-CRY9fHn7o'), 'chicken');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Tareewala Chicken in Pressure Cooker', 'Swad hi Swad', 'Indian', 5, 'https://www.youtube.com/watch?v=lWjs825fcjA', NULL, 'Alternative URLs:
- https://youtu.be/I_VyucZULRI
- https://www.youtube.com/watch?v=eIj1XKljIYs
- https://youtu.be/TiMZh9wrZKE', 1, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Tareewala Chicken in Pressure Cooker' AND youtube_url = 'https://www.youtube.com/watch?v=lWjs825fcjA'), 'tried');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Tareewala Chicken in Pressure Cooker' AND youtube_url = 'https://www.youtube.com/watch?v=lWjs825fcjA'), 'chicken');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Chicken Changezi', NULL, 'Indian', 5, 'https://www.youtube.com/watch?v=4GdVa-49iEg', NULL, NULL, 1, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Chicken Changezi' AND youtube_url = 'https://www.youtube.com/watch?v=4GdVa-49iEg'), 'tried');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Chicken Changezi' AND youtube_url = 'https://www.youtube.com/watch?v=4GdVa-49iEg'), 'chicken');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Bihari Chicken', 'Swad hi Swad', 'Indian', 5, 'https://www.youtube.com/watch?v=G5CfdH6OyG0', NULL, 'Alternative URLs:
- https://www.youtube.com/watch?v=ETEdeSsK5XE', 1, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Bihari Chicken' AND youtube_url = 'https://www.youtube.com/watch?v=G5CfdH6OyG0'), 'tried');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Bihari Chicken' AND youtube_url = 'https://www.youtube.com/watch?v=G5CfdH6OyG0'), 'chicken');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Kashmiri Chicken', NULL, 'Indian', 5, 'https://www.youtube.com/watch?v=nVzBt46m1Q8', NULL, NULL, 1, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Kashmiri Chicken' AND youtube_url = 'https://www.youtube.com/watch?v=nVzBt46m1Q8'), 'tried');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Kashmiri Chicken' AND youtube_url = 'https://www.youtube.com/watch?v=nVzBt46m1Q8'), 'chicken');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Punjabi Tareewala Chicken', NULL, 'Indian', 5, 'https://www.youtube.com/watch?v=BkB-jkA25gc', NULL, NULL, 1, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Punjabi Tareewala Chicken' AND youtube_url = 'https://www.youtube.com/watch?v=BkB-jkA25gc'), 'tried');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Punjabi Tareewala Chicken' AND youtube_url = 'https://www.youtube.com/watch?v=BkB-jkA25gc'), 'chicken');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Kolhapuri Chicken', NULL, 'Indian', 5, 'https://www.youtube.com/watch?v=j6D5y38FgKU', NULL, NULL, 1, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Kolhapuri Chicken' AND youtube_url = 'https://www.youtube.com/watch?v=j6D5y38FgKU'), 'tried');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Kolhapuri Chicken' AND youtube_url = 'https://www.youtube.com/watch?v=j6D5y38FgKU'), 'chicken');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Hyderabadi wedding Special Red Chicken', NULL, 'Indian', 5, 'https://www.youtube.com/watch?v=uvh2W16cAkI', NULL, NULL, 1, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Hyderabadi wedding Special Red Chicken' AND youtube_url = 'https://www.youtube.com/watch?v=uvh2W16cAkI'), 'tried');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Hyderabadi wedding Special Red Chicken' AND youtube_url = 'https://www.youtube.com/watch?v=uvh2W16cAkI'), 'chicken');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Chicken Salan', 'Swad hi Swad', 'Indian', 5, 'https://www.youtube.com/watch?v=VrKbnOl4HhY', NULL, NULL, 1, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Chicken Salan' AND youtube_url = 'https://www.youtube.com/watch?v=VrKbnOl4HhY'), 'tried');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Chicken Salan' AND youtube_url = 'https://www.youtube.com/watch?v=VrKbnOl4HhY'), 'chicken');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Maharastian Malvani chicken', 'Sanjyot Keer', 'Indian', 5, 'https://www.youtube.com/watch?v=hoS6EIUxn-4&t=10s', NULL, NULL, 1, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Maharastian Malvani chicken' AND youtube_url = 'https://www.youtube.com/watch?v=hoS6EIUxn-4&t=10s'), 'tried');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Maharastian Malvani chicken' AND youtube_url = 'https://www.youtube.com/watch?v=hoS6EIUxn-4&t=10s'), 'chicken');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Chicken Chatpata Gravy', NULL, 'Indian', 5, 'https://www.youtube.com/watch?v=NcoqkjSQFUQ', NULL, NULL, 1, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Chicken Chatpata Gravy' AND youtube_url = 'https://www.youtube.com/watch?v=NcoqkjSQFUQ'), 'tried');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Chicken Chatpata Gravy' AND youtube_url = 'https://www.youtube.com/watch?v=NcoqkjSQFUQ'), 'chicken');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Butter Chicken', NULL, 'Indian', 5, 'https://www.youtube.com/watch?v=913xQZBG1yE', NULL, 'Alternative URLs:
- https://www.youtube.com/watch?v=RKNogWbAivY
- https://www.youtube.com/watch?v=aR0IiJbxm4Q
- https://www.youtube.com/watch?v=F_4TzK27EBs&t=67s
- https://www.youtube.com/watch?v=bevpBpqS2ao', 1, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Butter Chicken' AND youtube_url = 'https://www.youtube.com/watch?v=913xQZBG1yE'), 'tried');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Butter Chicken' AND youtube_url = 'https://www.youtube.com/watch?v=913xQZBG1yE'), 'chicken');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Butter Chicken' AND youtube_url = 'https://www.youtube.com/watch?v=913xQZBG1yE'), 'butter');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Dhaba Style Chicken Curry', 'Swad hi Swad', 'Indian', 5, 'https://youtu.be/o3vnEj_bUvw', NULL, NULL, 1, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Dhaba Style Chicken Curry' AND youtube_url = 'https://youtu.be/o3vnEj_bUvw'), 'tried');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Dhaba Style Chicken Curry' AND youtube_url = 'https://youtu.be/o3vnEj_bUvw'), 'chicken');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Muglai Chicken Curry', 'Bharat Chicken', 'Indian', 5, 'https://www.youtube.com/watch?v=pVQudGeamec', NULL, NULL, 1, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Muglai Chicken Curry' AND youtube_url = 'https://www.youtube.com/watch?v=pVQudGeamec'), 'tried');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Muglai Chicken Curry' AND youtube_url = 'https://www.youtube.com/watch?v=pVQudGeamec'), 'chicken');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Chicken Butter Masala', 'Sanjyot Keer', 'Indian', 5, 'https://youtu.be/lyBGqv7IWaQ', NULL, NULL, 1, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Chicken Butter Masala' AND youtube_url = 'https://youtu.be/lyBGqv7IWaQ'), 'tried');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Chicken Butter Masala' AND youtube_url = 'https://youtu.be/lyBGqv7IWaQ'), 'chicken');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Chicken Butter Masala' AND youtube_url = 'https://youtu.be/lyBGqv7IWaQ'), 'butter');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Punjabi Chicken Gravy', 'Ranveer Brar', 'Indian', 5, 'https://youtu.be/JH5swnkC8Ig', NULL, 'Alternative URLs:
- https://youtu.be/HFyZgLHEyLI', 1, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Punjabi Chicken Gravy' AND youtube_url = 'https://youtu.be/JH5swnkC8Ig'), 'tried');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Punjabi Chicken Gravy' AND youtube_url = 'https://youtu.be/JH5swnkC8Ig'), 'chicken');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Chicken Angara', NULL, 'Indian', 5, 'https://youtu.be/QtUQ2rnK3a8', NULL, NULL, 1, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Chicken Angara' AND youtube_url = 'https://youtu.be/QtUQ2rnK3a8'), 'tried');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Chicken Angara' AND youtube_url = 'https://youtu.be/QtUQ2rnK3a8'), 'chicken');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Hyderabadi Chilli Chicken', NULL, 'Indian', 5, 'https://www.youtube.com/watch?v=ElMhRll8JCc&t=21s', NULL, NULL, 1, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Hyderabadi Chilli Chicken' AND youtube_url = 'https://www.youtube.com/watch?v=ElMhRll8JCc&t=21s'), 'tried');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Hyderabadi Chilli Chicken' AND youtube_url = 'https://www.youtube.com/watch?v=ElMhRll8JCc&t=21s'), 'chicken');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Hyderabadi Chicken Biryani', NULL, 'Indian', 5, 'https://youtu.be/cbgTasNQNPU', NULL, NULL, 1, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Hyderabadi Chicken Biryani' AND youtube_url = 'https://youtu.be/cbgTasNQNPU'), 'tried');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Hyderabadi Chicken Biryani' AND youtube_url = 'https://youtu.be/cbgTasNQNPU'), 'chicken');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Hyderabadi Chicken Biryani' AND youtube_url = 'https://youtu.be/cbgTasNQNPU'), 'biryani');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Paneer Bhurji', 'Ranveer Brar', 'Indian', 5, 'https://youtu.be/-w5uBstq3Ok', NULL, NULL, 1, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Paneer Bhurji' AND youtube_url = 'https://youtu.be/-w5uBstq3Ok'), 'tried');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Paneer Bhurji' AND youtube_url = 'https://youtu.be/-w5uBstq3Ok'), 'paneer');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Punjabi Chicken Masala', NULL, 'Indian', 0, 'https://youtu.be/qBqXzvSqEaU', NULL, NULL, 0, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Punjabi Chicken Masala' AND youtube_url = 'https://youtu.be/qBqXzvSqEaU'), 'chicken');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Butter Chicken Old Delhi Style', 'Ranveer Brar', 'Indian', 0, 'https://youtu.be/-LueyspwzwM', NULL, NULL, 0, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Butter Chicken Old Delhi Style' AND youtube_url = 'https://youtu.be/-LueyspwzwM'), 'chicken');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Butter Chicken Old Delhi Style' AND youtube_url = 'https://youtu.be/-LueyspwzwM'), 'butter');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Hyderabadi Masala Chicken', NULL, 'Indian', 0, 'https://www.youtube.com/watch?v=FhpyI2pWfMI', NULL, NULL, 0, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Hyderabadi Masala Chicken' AND youtube_url = 'https://www.youtube.com/watch?v=FhpyI2pWfMI'), 'chicken');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Tandoori chicken Tikka', NULL, 'Indian', 0, 'https://youtu.be/TXu10SDxyRY', NULL, NULL, 0, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Tandoori chicken Tikka' AND youtube_url = 'https://youtu.be/TXu10SDxyRY'), 'chicken');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Tandoori chicken Tikka' AND youtube_url = 'https://youtu.be/TXu10SDxyRY'), 'tikka');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Chicken Curry', 'Sanjyot Keer', 'Indian', 0, 'https://youtu.be/pAjrJna1TQE', NULL, NULL, 0, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Chicken Curry' AND youtube_url = 'https://youtu.be/pAjrJna1TQE'), 'chicken');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Andhra Chilli Chicken', 'Spice Eats', 'Indian', 0, 'https://youtu.be/pJXNSGLEiNw', NULL, NULL, 0, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Andhra Chilli Chicken' AND youtube_url = 'https://youtu.be/pJXNSGLEiNw'), 'chicken');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Punjabi Tareewala Kukad', 'Ranveer Brar', 'Indian', 0, 'https://youtu.be/wwmwnbM0m7k', NULL, NULL, 0, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Hostel chicken Curry', 'Ranveer Brar', 'Indian', 0, 'https://youtu.be/zmdp4DmRlIg', NULL, NULL, 0, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Hostel chicken Curry' AND youtube_url = 'https://youtu.be/zmdp4DmRlIg'), 'chicken');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Madras Masala Chicken Gravy', 'Spice Eats', 'Indian', 0, 'https://youtu.be/899gvhvZbrE', NULL, NULL, 0, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Madras Masala Chicken Gravy' AND youtube_url = 'https://youtu.be/899gvhvZbrE'), 'chicken');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Traditional Chicken Handi', 'Swad hi Swad', 'Indian', 0, 'https://youtu.be/FboHV4F01f4', NULL, NULL, 0, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Traditional Chicken Handi' AND youtube_url = 'https://youtu.be/FboHV4F01f4'), 'chicken');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Traditional Chicken Handi' AND youtube_url = 'https://youtu.be/FboHV4F01f4'), 'handi');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Karahi Chicken', 'Swad hi Swad', 'Indian', 0, 'https://youtu.be/Hzw_-xuWYck', NULL, NULL, 0, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Karahi Chicken' AND youtube_url = 'https://youtu.be/Hzw_-xuWYck'), 'chicken');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Village Style Chicken Curry', NULL, 'Indian', 0, 'https://youtu.be/ifR9cMNzheM', NULL, NULL, 0, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Village Style Chicken Curry' AND youtube_url = 'https://youtu.be/ifR9cMNzheM'), 'chicken');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Chicken Tikka Masala', 'Sanjyot Keer', 'Indian', 0, 'https://www.youtube.com/watch?v=wm5vqZcl8BQ', NULL, 'Alternative URLs:
- https://youtu.be/c2MGcq_m6r4', 0, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Chicken Tikka Masala' AND youtube_url = 'https://www.youtube.com/watch?v=wm5vqZcl8BQ'), 'chicken');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Chicken Tikka Masala' AND youtube_url = 'https://www.youtube.com/watch?v=wm5vqZcl8BQ'), 'tikka');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Chilli Chicken (Chinese)', 'Sanjyot Keer', 'Indian', 0, 'https://youtu.be/UhSlMykeesQ', NULL, NULL, 0, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Chilli Chicken (Chinese)' AND youtube_url = 'https://youtu.be/UhSlMykeesQ'), 'chicken');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Chicken Jahanpanah', NULL, 'Indian', 0, 'https://youtu.be/yTefXqk1_fQ', NULL, 'Alternative URLs:
- https://youtu.be/nBafYcuQR1Q', 0, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Chicken Jahanpanah' AND youtube_url = 'https://youtu.be/yTefXqk1_fQ'), 'chicken');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Chicken Hungama', NULL, 'Indian', 0, 'https://youtu.be/CGt7tFGvRAI', NULL, NULL, 0, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Chicken Hungama' AND youtube_url = 'https://youtu.be/CGt7tFGvRAI'), 'chicken');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Chicken Korma', NULL, 'Indian', 0, 'https://youtu.be/DjqqFuTCovc', NULL, NULL, 0, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Chicken Korma' AND youtube_url = 'https://youtu.be/DjqqFuTCovc'), 'chicken');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Chicken Korma' AND youtube_url = 'https://youtu.be/DjqqFuTCovc'), 'korma');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Dhaba Style Chicken Handi', 'Sanjyot Keer', 'Indian', 0, 'https://www.youtube.com/watch?v=iQeM9uDW05Y&t=8s', NULL, NULL, 0, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Dhaba Style Chicken Handi' AND youtube_url = 'https://www.youtube.com/watch?v=iQeM9uDW05Y&t=8s'), 'chicken');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Dhaba Style Chicken Handi' AND youtube_url = 'https://www.youtube.com/watch?v=iQeM9uDW05Y&t=8s'), 'handi');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Chicken Curry', 'Bharat Chicken', 'Indian', 0, 'https://www.youtube.com/watch?v=4YvU89XzS8w', NULL, 'Alternative URLs:
- https://www.youtube.com/watch?v=2dsinHcq5eM', 0, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Chicken Curry' AND youtube_url = 'https://www.youtube.com/watch?v=4YvU89XzS8w'), 'chicken');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Maharastrian Gavran Chicken Rassa', NULL, 'Indian', 0, 'https://www.youtube.com/watch?v=mHp-151spQA', NULL, NULL, 0, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Maharastrian Gavran Chicken Rassa' AND youtube_url = 'https://www.youtube.com/watch?v=mHp-151spQA'), 'chicken');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Kadhai Chicken', 'Swad hi Swad', 'Indian', 0, 'https://youtu.be/wFTE9Gl1ldc', NULL, NULL, 0, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Kadhai Chicken' AND youtube_url = 'https://youtu.be/wFTE9Gl1ldc'), 'chicken');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Tawa Chicken', NULL, 'Indian', 0, 'https://www.youtube.com/watch?v=-Y1p7mu-b_M', NULL, NULL, 0, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Tawa Chicken' AND youtube_url = 'https://www.youtube.com/watch?v=-Y1p7mu-b_M'), 'chicken');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Muglai Chicken Handi', NULL, 'Indian', 0, 'https://www.youtube.com/watch?v=u66pG73UroY', NULL, NULL, 0, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Muglai Chicken Handi' AND youtube_url = 'https://www.youtube.com/watch?v=u66pG73UroY'), 'chicken');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Muglai Chicken Handi' AND youtube_url = 'https://www.youtube.com/watch?v=u66pG73UroY'), 'handi');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Chicken Maharani', NULL, 'Indian', 0, 'https://www.youtube.com/watch?v=8gNvwhmsK4g', NULL, NULL, 0, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Chicken Maharani' AND youtube_url = 'https://www.youtube.com/watch?v=8gNvwhmsK4g'), 'chicken');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Chicken Lababdar', NULL, 'Indian', 0, 'https://www.youtube.com/watch?v=UgJq1MZEzFI', NULL, NULL, 0, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Chicken Lababdar' AND youtube_url = 'https://www.youtube.com/watch?v=UgJq1MZEzFI'), 'chicken');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Simple Chicken Masala', NULL, 'Indian', 0, 'https://www.youtube.com/watch?v=UW_FQp6EgUM', NULL, NULL, 0, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Simple Chicken Masala' AND youtube_url = 'https://www.youtube.com/watch?v=UW_FQp6EgUM'), 'chicken');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('North Indian Spicy Chicken Masala', NULL, 'Indian', 0, 'https://www.youtube.com/watch?v=iHEW-eN8LCg', NULL, NULL, 0, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'North Indian Spicy Chicken Masala' AND youtube_url = 'https://www.youtube.com/watch?v=iHEW-eN8LCg'), 'chicken');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Butter Chicken Pakistan Style', NULL, 'Indian', 0, 'https://www.youtube.com/watch?v=JY6f1V3Qves', NULL, NULL, 0, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Butter Chicken Pakistan Style' AND youtube_url = 'https://www.youtube.com/watch?v=JY6f1V3Qves'), 'chicken');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Butter Chicken Pakistan Style' AND youtube_url = 'https://www.youtube.com/watch?v=JY6f1V3Qves'), 'butter');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Chicken Makhani Handi', NULL, 'Indian', 0, 'https://www.youtube.com/watch?v=fiCZ6ikcTVw', NULL, NULL, 0, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Chicken Makhani Handi' AND youtube_url = 'https://www.youtube.com/watch?v=fiCZ6ikcTVw'), 'chicken');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Chicken Makhani Handi' AND youtube_url = 'https://www.youtube.com/watch?v=fiCZ6ikcTVw'), 'handi');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Patiala Chicken', NULL, 'Indian', 0, 'https://www.youtube.com/watch?v=O23PR-JHHSA', NULL, NULL, 0, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Patiala Chicken' AND youtube_url = 'https://www.youtube.com/watch?v=O23PR-JHHSA'), 'chicken');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Hyderabadi Dum Ka Murg', NULL, 'Indian', 0, 'https://www.youtube.com/watch?v=o5sAAM5DUmg', NULL, NULL, 0, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Chicken Bhuna Masala', 'Swad hi Swad', 'Indian', 0, 'https://www.youtube.com/watch?v=a2a1HtBBTug', NULL, 'Alternative URLs:
- https://www.youtube.com/watch?v=MScesHB_OmA
- https://youtu.be/rmJ2pwXz1Yc', 0, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Chicken Bhuna Masala' AND youtube_url = 'https://www.youtube.com/watch?v=a2a1HtBBTug'), 'chicken');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Bachelor Style Chicken Gravy', NULL, 'Indian', 0, 'https://www.youtube.com/watch?v=vaaY6GRmkDw', NULL, NULL, 0, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Bachelor Style Chicken Gravy' AND youtube_url = 'https://www.youtube.com/watch?v=vaaY6GRmkDw'), 'chicken');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Muslim Style Chicken Curry in Pressure Cooker', NULL, 'Indian', 0, 'https://www.youtube.com/watch?v=NeBHsG90-4M', NULL, NULL, 0, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Muslim Style Chicken Curry in Pressure Cooker' AND youtube_url = 'https://www.youtube.com/watch?v=NeBHsG90-4M'), 'chicken');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Kasuri Methi Malai Chciken', NULL, 'Indian', 0, 'https://www.youtube.com/watch?v=H9prlRqsAfI', NULL, NULL, 0, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Curry Leaf Chicken Curry', NULL, 'Indian', 0, 'https://www.youtube.com/watch?v=_OXMsU-qGdg', NULL, NULL, 0, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Curry Leaf Chicken Curry' AND youtube_url = 'https://www.youtube.com/watch?v=_OXMsU-qGdg'), 'chicken');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Muglai chicken', NULL, 'Indian', 0, 'https://www.youtube.com/watch?v=ulRj6PuUe_c', NULL, NULL, 0, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Muglai chicken' AND youtube_url = 'https://www.youtube.com/watch?v=ulRj6PuUe_c'), 'chicken');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Chicken Korma', NULL, 'Indian', 0, 'https://www.youtube.com/watch?v=6M8vK2CkrFs', NULL, NULL, 0, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Chicken Korma' AND youtube_url = 'https://www.youtube.com/watch?v=6M8vK2CkrFs'), 'chicken');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Chicken Korma' AND youtube_url = 'https://www.youtube.com/watch?v=6M8vK2CkrFs'), 'korma');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('North Indian Style Chicken Masala', NULL, 'Indian', 0, 'https://www.youtube.com/watch?v=iHEW-eN8LCg&t=4s', NULL, NULL, 0, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'North Indian Style Chicken Masala' AND youtube_url = 'https://www.youtube.com/watch?v=iHEW-eN8LCg&t=4s'), 'chicken');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Pakistan Chicken Curry', NULL, 'Indian', 0, 'https://www.youtube.com/watch?v=1HP1YCpWx_U', NULL, NULL, 0, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Pakistan Chicken Curry' AND youtube_url = 'https://www.youtube.com/watch?v=1HP1YCpWx_U'), 'chicken');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Chicken Karahi / Lahori Chicken', NULL, 'Indian', 0, 'https://www.youtube.com/watch?v=Sbta5Bodyc8', NULL, NULL, 0, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Chicken Karahi / Lahori Chicken' AND youtube_url = 'https://www.youtube.com/watch?v=Sbta5Bodyc8'), 'chicken');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Nizami Dum Ka Murgh', NULL, 'Indian', 0, 'https://www.youtube.com/watch?v=zZX1pDtU_yQ', NULL, NULL, 0, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Lohori Green Chicken', NULL, 'Indian', 0, 'https://www.youtube.com/watch?v=KJJCyRK6IwY', NULL, NULL, 0, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Lohori Green Chicken' AND youtube_url = 'https://www.youtube.com/watch?v=KJJCyRK6IwY'), 'chicken');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Shahi Murg Masala', NULL, 'Indian', 0, 'https://www.youtube.com/watch?v=81aToonNyQc', NULL, NULL, 0, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Chicken Kheema', NULL, 'Indian', 0, 'https://youtu.be/XUCVgcbhnlg', NULL, 'Alternative URLs:
- https://youtu.be/hNAHNsc8_Vw', 0, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Chicken Kheema' AND youtube_url = 'https://youtu.be/XUCVgcbhnlg'), 'chicken');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Chicken Kheema' AND youtube_url = 'https://youtu.be/XUCVgcbhnlg'), 'kheema');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Egg Butter Masala', 'Sanjyot Keer', 'Indian', 0, 'https://youtu.be/tqb686TwZF8', NULL, NULL, 0, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Egg Butter Masala' AND youtube_url = 'https://youtu.be/tqb686TwZF8'), 'egg');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Egg Butter Masala' AND youtube_url = 'https://youtu.be/tqb686TwZF8'), 'butter');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Egg Curry', NULL, 'Indian', 0, 'https://www.youtube.com/watch?v=4jC-rX3iAMY', NULL, 'Alternative URLs:
- https://www.youtube.com/watch?v=_BA9OiyjReQ
- https://www.youtube.com/watch?v=Vr3BhPCOZh8&t=19s', 0, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Egg Curry' AND youtube_url = 'https://www.youtube.com/watch?v=4jC-rX3iAMY'), 'egg');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Palak Egg Cury', NULL, 'Indian', 0, 'https://www.youtube.com/watch?v=qO_XokPUpqc', NULL, NULL, 0, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Palak Egg Cury' AND youtube_url = 'https://www.youtube.com/watch?v=qO_XokPUpqc'), 'egg');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Dhaba Style Anda Masala', NULL, 'Indian', 0, 'https://youtu.be/CbZxp8bwErM', NULL, NULL, 0, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Dhaba Style Anda Masala' AND youtube_url = 'https://youtu.be/CbZxp8bwErM'), 'egg');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Crated Egg Curry', NULL, 'Indian', 0, 'https://www.youtube.com/watch?v=WTr31nLTt5U', NULL, NULL, 0, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Crated Egg Curry' AND youtube_url = 'https://www.youtube.com/watch?v=WTr31nLTt5U'), 'egg');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Egg Kheema Dhaba Style', 'Swad hi swad', 'Indian', 0, 'https://www.youtube.com/watch?v=uMlnpOuZIWk', NULL, NULL, 0, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Egg Kheema Dhaba Style' AND youtube_url = 'https://www.youtube.com/watch?v=uMlnpOuZIWk'), 'egg');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Egg Kheema Dhaba Style' AND youtube_url = 'https://www.youtube.com/watch?v=uMlnpOuZIWk'), 'kheema');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Spicy Egg Curry', 'Ranveer Brar', 'Indian', 0, 'https://youtu.be/pqGMxHIfcXg', NULL, NULL, 0, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Spicy Egg Curry' AND youtube_url = 'https://youtu.be/pqGMxHIfcXg'), 'egg');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Egg Chilly', NULL, 'Indian', 0, 'https://www.youtube.com/watch?v=8C-Z5YlJ36Y', NULL, NULL, 0, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Egg Chilly' AND youtube_url = 'https://www.youtube.com/watch?v=8C-Z5YlJ36Y'), 'egg');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Anda Masala', NULL, 'Indian', 0, 'https://youtu.be/IOSqLj75zbU', NULL, NULL, 0, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Anda Masala' AND youtube_url = 'https://youtu.be/IOSqLj75zbU'), 'egg');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Kalyani Chicken Biryani', NULL, 'Indian', 0, 'https://www.youtube.com/watch?v=1jBR44q1Pn4', NULL, NULL, 0, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Kalyani Chicken Biryani' AND youtube_url = 'https://www.youtube.com/watch?v=1jBR44q1Pn4'), 'chicken');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Kalyani Chicken Biryani' AND youtube_url = 'https://www.youtube.com/watch?v=1jBR44q1Pn4'), 'biryani');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Chatpati Spicy Chicken Biryani', NULL, 'Indian', 0, 'https://youtu.be/Ksn_5RHqZlY', NULL, NULL, 0, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Chatpati Spicy Chicken Biryani' AND youtube_url = 'https://youtu.be/Ksn_5RHqZlY'), 'chicken');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Chatpati Spicy Chicken Biryani' AND youtube_url = 'https://youtu.be/Ksn_5RHqZlY'), 'biryani');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Maggie', NULL, 'Indian', 0, 'https://youtu.be/425TvzG85Sc', NULL, NULL, 0, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Chicken Soup', 'Chef Ashok', 'Indian', 0, 'https://youtu.be/gFlEbpaCuBw', NULL, 'Alternative URLs:
- https://youtu.be/Y2Zh4v9YwT4', 0, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Chicken Soup' AND youtube_url = 'https://youtu.be/gFlEbpaCuBw'), 'chicken');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Chicken Soup' AND youtube_url = 'https://youtu.be/gFlEbpaCuBw'), 'soup');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Manchow Soup', NULL, 'Indian', 0, 'https://youtu.be/msmMHiOn7NU', NULL, NULL, 0, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Manchow Soup' AND youtube_url = 'https://youtu.be/msmMHiOn7NU'), 'soup');
INSERT INTO recipe (title, author, cuisine, rating, youtube_url, thumbnail_path, notes_md, is_favourite, added_at) VALUES ('Egg Tikka Masala', NULL, 'Indian', 0, 'https://youtu.be/pxAlG7BHHxs', NULL, NULL, 0, '2026-05-03T09:41:20.808Z');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Egg Tikka Masala' AND youtube_url = 'https://youtu.be/pxAlG7BHHxs'), 'egg');
INSERT INTO recipe_tag (recipe_id, tag) VALUES ((SELECT id FROM recipe WHERE title = 'Egg Tikka Masala' AND youtube_url = 'https://youtu.be/pxAlG7BHHxs'), 'tikka');